"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function LegalPage() {
  const searchParams = useSearchParams();
  const [activeTab, setActiveTab] = useState("terms");

  useEffect(() => {
    // Get the hash from the URL to set the active tab
    const hash =
      searchParams.get("tab") || window.location.hash.replace("#", "");
    if (hash && ["terms", "privacy", "cookies"].includes(hash)) {
      setActiveTab(hash);
    }
  }, [searchParams]);

  return (
    <div className="container mx-auto px-4 pt-24 pb-12">
      <h1 className="text-3xl font-bold mb-8 text-center">Legal Policies</h1>

      <Tabs
        value={activeTab}
        onValueChange={setActiveTab}
        className="max-w-4xl mx-auto"
      >
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="terms">Terms of Service</TabsTrigger>
          <TabsTrigger value="privacy">Privacy Policy</TabsTrigger>
          <TabsTrigger value="cookies">Cookie Policy</TabsTrigger>
        </TabsList>

        <TabsContent value="terms" className="mt-6">
          <div className="prose prose-invert max-w-none">
            <h2 className="text-2xl font-semibold mb-4">Terms of Service</h2>

            <h3 className="text-xl font-medium mt-6 mb-3">1. Introduction</h3>
            <p>
              Welcome to AI Career Coach. These Terms of Service govern your use
              of our website and services. By accessing or using our services,
              you agree to be bound by these Terms.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">
              2. Services Description
            </h3>
            <p>
              AI Career Coach provides AI-powered career development tools
              including resume building, interview preparation, and cover letter
              generation. Our services use artificial intelligence to provide
              personalized career guidance and document creation.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">3. User Accounts</h3>
            <p>
              To access certain features of our services, you may need to create
              an account. You are responsible for maintaining the
              confidentiality of your account information and for all activities
              that occur under your account.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">4. User Content</h3>
            <p>
              You retain ownership of any content you submit to our services. By
              submitting content, you grant us a non-exclusive, worldwide,
              royalty-free license to use, store, and process your content for
              the purpose of providing our services.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">
              5. Limitation of Liability
            </h3>
            <p>
              Our services are provided "as is" without warranties of any kind.
              We are not liable for any damages arising from your use of our
              services or any content generated by our AI tools.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">
              6. Changes to Terms
            </h3>
            <p>
              We may modify these Terms at any time. Continued use of our
              services after any such changes constitutes your acceptance of the
              new Terms.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">7. Termination</h3>
            <p>
              We reserve the right to terminate or suspend your account and
              access to our services at our sole discretion, without notice, for
              conduct that we believe violates these Terms or is harmful to
              other users, us, or third parties.
            </p>
          </div>
        </TabsContent>

        <TabsContent value="privacy" className="mt-6">
          <div className="prose prose-invert max-w-none">
            <h2 className="text-2xl font-semibold mb-4">Privacy Policy</h2>

            <h3 className="text-xl font-medium mt-6 mb-3">
              1. Information We Collect
            </h3>
            <p>
              We collect information you provide directly to us, such as when
              you create an account, use our services, or communicate with us.
              This may include personal information such as your name, email
              address, and resume data.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">
              2. How We Use Your Information
            </h3>
            <p>
              We use the information we collect to provide, maintain, and
              improve our services, to develop new services, and to protect our
              company and users. We may use your information to communicate with
              you about our services, to respond to your inquiries, and for
              other customer service purposes.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">
              3. Information Sharing
            </h3>
            <p>
              We do not share your personal information with third parties
              except as described in this Privacy Policy. We may share your
              information with service providers who perform services on our
              behalf, as required by law, or in connection with a merger,
              acquisition, or sale of all or a portion of our assets.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">4. Data Security</h3>
            <p>
              We take reasonable measures to help protect your personal
              information from loss, theft, misuse, and unauthorized access,
              disclosure, alteration, and destruction. However, no security
              system is impenetrable, and we cannot guarantee the security of
              our systems.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">5. Your Rights</h3>
            <p>
              You may access, update, or delete your account information at any
              time by logging into your account. You may also contact us to
              request access to, correction of, or deletion of personal
              information that you have provided to us.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">
              6. Changes to Privacy Policy
            </h3>
            <p>
              We may modify this Privacy Policy at any time. If we make material
              changes, we will notify you through our services or by other
              means, such as email.
            </p>
          </div>
        </TabsContent>

        <TabsContent value="cookies" className="mt-6">
          <div className="prose prose-invert max-w-none">
            <h2 className="text-2xl font-semibold mb-4">Cookie Policy</h2>

            <h3 className="text-xl font-medium mt-6 mb-3">
              1. What Are Cookies
            </h3>
            <p>
              Cookies are small text files that are placed on your device when
              you visit a website. They are widely used to make websites work
              more efficiently and provide information to the website owners.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">
              2. How We Use Cookies
            </h3>
            <p>We use cookies for various purposes, including:</p>
            <ul className="list-disc pl-6 mt-2 mb-4">
              <li>
                Essential cookies: These are necessary for the website to
                function properly.
              </li>
              <li>
                Analytical/performance cookies: These allow us to recognize and
                count the number of visitors and see how visitors move around
                our website.
              </li>
              <li>
                Functionality cookies: These are used to recognize you when you
                return to our website.
              </li>
              <li>
                Targeting cookies: These record your visit to our website, the
                pages you have visited, and the links you have followed.
              </li>
            </ul>

            <h3 className="text-xl font-medium mt-6 mb-3">
              3. Third-Party Cookies
            </h3>
            <p>
              Some cookies are placed by third parties on our website. These
              third parties may include analytics providers, advertising
              networks, and social media platforms. These third parties may use
              cookies, alone or in conjunction with web beacons or other
              tracking technologies, to collect information about you when you
              use our website.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">
              4. Managing Cookies
            </h3>
            <p>
              Most web browsers allow you to control cookies through their
              settings. You can usually find these settings in the "options" or
              "preferences" menu of your browser. You can also delete cookies
              that have already been set.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">
              5. Changes to Cookie Policy
            </h3>
            <p>
              We may update this Cookie Policy from time to time to reflect
              changes in technology, regulation, or our business practices. Any
              changes will be posted on this page, and if the changes are
              significant, we will provide a more prominent notice.
            </p>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
